### ISSUE TITLE
[BOUNTY] Build revamped subgraph for VoxoDeus NFT

### ISSUE THREAD

**Issue by araa47** [voxodeus/cypher-subgraph#1]
The following is an issue for bounty, meant for external contributors to pick up and work on the analytics of VoxoDeus NFT.

# Introduction

[VoxoDeus](https://voxodeus.io/) is the first large scale interactive 3d NFT collectibles on the Ethereum Blockchain. 

The VoxoDeus contract can be explored over [here](https://etherscan.io/address/0xafbA8C6B3875868a90E5055e791213258a9fe7a7#code)

# Task Description 

This project requires to build out a subgraph for the VoxoDeus NFT with the following requirements:  

1. Able to query a list of all minters efficiently 
2. Able to query a list of all holders efficiently 
3. Able to query a list of current holders efficiently 
4. Able to query by user address, and this should show the unique ids of VoxoDeus NFT’s minted + held + historically owned + numbers for each 
5. Able to query a list of top minters, top holders and top historical holders 

# Bonus Task
1. Able to query a list of all sales related to VoxoDeus NFT on OpenSea 
2. Able to query a list of sales by user for VoxoDeus NFT’s 

# Definition of Complete 

[ ] Working subgraph explorer on [TheGraph](https://thegraph.com/)
[ ] Create a PR into this repo with the new working subgraph 
[ ] Completed all the requirements described in *Task Description* section 
[ ] Sample queries for the tasks described in *Task Description* section 
[ ] Documentation of the subgraph 

# Useful Resources 

An example subgraph is also available [here](https://github.com/voxodeus/voxo-subgraph/). Note that this sample was hacked together pretty quickly in the past and may not be accurate, and doesn’t have the entities required to be able to match the requirements above, but should be a good starting point.

**Comment by gitcoinbot** [comment]
@hhio618 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=1) | [3 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=3) | [5 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=5) | [10 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=10) | [100 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=100)

**Comment by gitcoinbot** [comment]
@amantulsyan35 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=1) | [3 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=3) | [5 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=5) | [10 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=10) | [100 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=100)

**Comment by gitcoinbot** [comment]
@amantulsyan35 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=1) | [3 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=3) | [5 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=5) | [10 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=10) | [100 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=100)

**Comment by gitcoinbot** [comment]
@hhio618 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=1) | [3 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=3) | [5 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=5) | [10 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=10) | [100 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=100)

**Comment by gitcoinbot** [comment]
@amantulsyan35 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=1) | [3 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=3) | [5 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=5) | [10 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=10) | [100 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=100)

**Comment by gitcoinbot** [comment]
@amantulsyan35 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=1) | [3 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=3) | [5 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=5) | [10 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=10) | [100 days](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

__Work for 1.5 ETH (4867.75 USD @ $3245.17/ETH) has been submitted by__:

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $3,708,934.08 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 265 years, 2 months from now.
Please review their action plans below:


**1) [hhio618](https://gitcoin.co/hhio618) has been approved to start work.**

I'm experienced with subgraph.
My Plan:
1- Read the contract
1- Implementing the subgraph

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/voxodeus/voxo-subgraph/1/100026262).
